# -*- coding: utf-8 -*-
"""
One-shot export of predict-history + risk-history JSON for static hosting (no Flask server).

Usage (from repo root):
  python tools/export_static_predict_history.py
  python tools/export_static_predict_history.py --days 300
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone


def _repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def _frontend_data_dir() -> str:
    return os.path.join(_repo_root(), "src", "frontend", "public", "data")

def _legacy_web_frontend_data_dir() -> str:
    """Legacy inline-Babel frontend expects data under web/frontend/data/."""
    return os.path.join(_repo_root(), "web", "frontend", "data")


def _json_safe(obj):
    """Recursively convert numpy/pandas scalars for json.dump."""
    try:
        import numpy as np
    except ImportError:
        np = None  # type: ignore
    try:
        import pandas as pd
    except ImportError:
        pd = None  # type: ignore

    if isinstance(obj, dict):
        return {k: _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_json_safe(v) for v in obj]
    if np is not None:
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
    if pd is not None and isinstance(obj, pd.Timestamp):
        return obj.isoformat()
    if hasattr(obj, "item") and callable(getattr(obj, "item")):
        try:
            return _json_safe(obj.item())
        except Exception:
            pass
    return obj


def _write_static_data_js(out_dir: str, predict_result: dict, manifest: dict, risk_result: dict) -> str:
    """Emit JS shim so file:// pages can load data without fetch (CORS on null origin)."""
    path = os.path.join(out_dir, "static-data.js")

    def esc_json(s: str) -> str:
        return s.replace("</", "<\\/")

    pj = esc_json(json.dumps(predict_result, ensure_ascii=False))
    mj = esc_json(json.dumps(manifest, ensure_ascii=False))
    rj = esc_json(json.dumps(risk_result, ensure_ascii=False))
    content = (
        "// Auto-generated by tools/export_static_predict_history.py\n"
        f"window.__STATIC_PREDICT_HISTORY__ = {pj};\n"
        f"window.__STATIC_MANIFEST__ = {mj};\n"
        f"window.__STATIC_RISK_HISTORY__ = {rj};\n"
    )
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    generated_path = os.path.join(out_dir, "static-data.generated.js")
    with open(generated_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    embed_path = os.path.join(out_dir, "predict-history.embed.js")
    with open(embed_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    embed_txt_path = os.path.join(out_dir, "predict-history.embed.txt")
    with open(embed_txt_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    # legacy inline index.html now also tries root-level embed first
    parent_dir = os.path.dirname(out_dir)
    if os.path.basename(parent_dir) == "frontend":
        root_embed_path = os.path.join(parent_dir, "predict-history.embed.js")
        with open(root_embed_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        root_embed_txt_path = os.path.join(parent_dir, "predict-history.embed.txt")
        with open(root_embed_txt_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
    return path


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="Export static JSON for both frontends (src/frontend + web/frontend).")
    parser.add_argument("--days", type=int, default=300, help="predict/history days (1-300)")
    args = parser.parse_args()
    days = args.days
    if days < 1 or days > 300:
        print("days must be 1-300", file=sys.stderr)
        return 2

    root = _repo_root()
    sys.path.insert(0, os.path.join(root, "src"))
    os.chdir(root)

    from backend.service.micro_cap_legacy_bridge import (  # noqa: PLC0415
        MicroCapLegacyFacade,
        get_legacy_facade,
    )

    MicroCapLegacyFacade.reset_singleton()
    facade = get_legacy_facade()

    print("Initializing analyzer + fetching market data...")
    ok = facade.ensure_data()
    if not ok:
        print("Warning: fetch_data returned False; export may fail or be empty.", file=sys.stderr)

    import utils.history_backtest_service as hbs_mod  # type: ignore  # noqa: PLC0415

    hbs_mod._history_service_instance = None  # type: ignore[attr-defined]

    history_service = facade.history_backtest()
    print(f"Computing predict history (days={days}, include_evaluation=True)...")
    predict_result = history_service.calculate_history(days, include_evaluation=True)
    predict_result = _json_safe(predict_result)

    risk_days = max(10, min(days, 300))
    risk_service = facade.history_risk()
    print(f"Computing risk history sample (days={risk_days})...")
    risk_result = risk_service.calculate_history(risk_days)
    risk_result = _json_safe(risk_result)

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source": "tools/export_static_predict_history.py",
        "days": days,
        "risk_sample_days": risk_days,
        "include_evaluation": True,
        "predict_success": predict_result.get("success"),
        "risk_success": risk_result.get("success"),
    }

    prob_meta = predict_result.get("metadata") or {}
    manifest.update(
        {
            "prob_model_params_version": prob_meta.get("prob_model_params_version"),
            "temperature_t1": prob_meta.get("temperature_t1"),
            "temperature_t5": prob_meta.get("temperature_t5"),
        }
    )

    out_dirs = [_frontend_data_dir(), _legacy_web_frontend_data_dir()]
    wrote = []
    for out_dir in out_dirs:
        os.makedirs(out_dir, exist_ok=True)

        pred_path = os.path.join(out_dir, f"predict_history_{days}.json")
        with open(pred_path, "w", encoding="utf-8") as f:
            json.dump(predict_result, f, ensure_ascii=False, indent=2)
        wrote.append(pred_path)

        # 兼容旧页面仍读取 predict_history_100.json 的场景
        compat_pred_path = os.path.join(out_dir, "predict_history_100.json")
        with open(compat_pred_path, "w", encoding="utf-8") as f:
            json.dump(predict_result, f, ensure_ascii=False, indent=2)
        wrote.append(compat_pred_path)

        risk_path = os.path.join(out_dir, "risk_history_sample.json")
        with open(risk_path, "w", encoding="utf-8") as f:
            json.dump(risk_result, f, ensure_ascii=False, indent=2)
        wrote.append(risk_path)

        manifest_path = os.path.join(out_dir, "manifest.json")
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, ensure_ascii=False, indent=2)
        wrote.append(manifest_path)

        js_path = _write_static_data_js(out_dir, predict_result, manifest, risk_result)
        wrote.append(js_path)

    print("Wrote:", "\n  ".join(wrote))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
